# Generated by Django 4.1.7 on 2026-02-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octofit_tracker', '0002_add_team_calories_to_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
